## Portfolio - Predicción de goles en partidos FIFA WC26

### Predicción

Imprimir la predicción de archivos

In [1]:
import pandas as pd
from tabulate import tabulate
import requests

In [2]:
url_t = "https://worldcup26.ir/get/teams"
response = requests.get(url_t)
teams = response.json()
teams_flag = {team['fifa_code']: team['flag'] for team in teams['teams']}

In [3]:
check = pd.read_parquet('../database/ranking_fifa.parquet')
#check[check['Codigo_Pais'].isin(['COD','UZB'])]

In [4]:
df = pd.read_parquet('../database/predictions_r2.parquet')
df['Flag'] = df['Team'].map(teams_flag)
df['Estimated_goals'] = df['Goles_Estimados'].copy()
df.sort_values(by=['Date','Venue'], inplace=True)
df['Estimated_goals2'] = df['Model_predict'].astype(int)
df_test = df[['Date','Team','Flag', 'Opponent', 'Model_predict','Estimated_goals', 'Estimated_goals2']]
df_test

,Date,Team,Flag,Opponent,Model_predict,Estimated_goals,Estimated_goals2
1,2026-07-18,ENG,https://flagcdn.com/w80/gb-eng.png,France,1.328049,1,1
3,2026-07-18,FRA,https://flagcdn.com/w80/fr.png,England,1.459476,1,1
0,2026-07-19,ARG,https://flagcdn.com/w80/ar.png,Spain,1.579974,2,1
2,2026-07-19,ESP,https://flagcdn.com/w80/es.png,Argentina,1.257231,1,1

In [7]:
filtro = df_test['Date'].dt.date == pd.Timestamp('2026-07-19').date()
df_hoy = df_test[filtro][['Team', 'Flag', 'Opponent', 'Estimated_goals','Estimated_goals2','Model_predict']]

In [8]:
from IPython.display import HTML

# Definimos una función para convertir URLs en etiquetas img
def path_to_image_html(path):
    return f'<img src="{path}" width="40" >'

# Aplicamos el estilo al DataFrame
# Esto creará una representación HTML donde los links serán imágenes visibles
html_output = df_hoy.to_html(
    escape=False, 
    formatters=dict(Flag=path_to_image_html)
)

# Mostramos el resultado
display(HTML(html_output))

In [28]:

df_print = df[['Date','Team','Opponent', 'Goles_Estimados']].copy() 
df_print['Date']=df_print['Date'].dt.strftime('%Y-%m-%d')
# Mostrar las primeras filas como tabla Markdown
print(df_print.sort_values(by=['Date','Team']).to_markdown(index=False))

| Date       | Team   | Opponent                         |   Goles_Estimados |
|:-----------|:-------|:---------------------------------|------------------:|
| 2026-06-24 | BIH    | Qatar                            |                 1 |
| 2026-06-24 | BRA    | Scotland                         |                 2 |
| 2026-06-24 | CAN    | Switzerland                      |                 1 |
| 2026-06-24 | CZE    | Mexico                           |                 1 |
| 2026-06-24 | HAI    | Morocco                          |                 1 |
| 2026-06-24 | KOR    | South Africa                     |                 2 |
| 2026-06-24 | MAR    | Haiti                            |                 3 |
| 2026-06-24 | MEX    | Czech Republic                   |                 2 |
| 2026-06-24 | QAT    | Bosnia and Herzegovina           |                 1 |
| 2026-06-24 | RSA    | South Korea                      |                 1 |
| 2026-06-24 | SCO    | Brazil                           |                 1 |
| 2026-06-24 | SUI    | Canada                           |                 2 |
| 2026-06-25 | AUS    | Paraguay                         |                 2 |
| 2026-06-25 | CIV    | Curaçao                          |                 2 |
| 2026-06-25 | CUW    | Ivory Coast                      |                 1 |
| 2026-06-25 | ECU    | Germany                          |                 1 |
| 2026-06-25 | GER    | Ecuador                          |                 2 |
| 2026-06-25 | JPN    | Sweden                           |                 2 |
| 2026-06-25 | NED    | Tunisia                          |                 2 |
| 2026-06-25 | PAR    | Australia                        |                 1 |
| 2026-06-25 | SWE    | Japan                            |                 1 |
| 2026-06-25 | TUN    | Netherlands                      |                 1 |
| 2026-06-25 | TUR    | United States                    |                 1 |
| 2026-06-25 | USA    | Turkey                           |                 2 |
| 2026-06-26 | BEL    | New Zealand                      |                 3 |
| 2026-06-26 | CPV    | Saudi Arabia                     |                 1 |
| 2026-06-26 | EGY    | Iran                             |                 1 |
| 2026-06-26 | ESP    | Uruguay                          |                 2 |
| 2026-06-26 | FRA    | Norway                           |                 2 |
| 2026-06-26 | IRN    | Egypt                            |                 2 |
| 2026-06-26 | IRQ    | Senegal                          |                 1 |
| 2026-06-26 | KSA    | Cape Verde                       |                 1 |
| 2026-06-26 | NOR    | France                           |                 1 |
| 2026-06-26 | NZL    | Belgium                          |                 1 |
| 2026-06-26 | SEN    | Iraq                             |                 2 |
| 2026-06-26 | URU    | Spain                            |                 1 |
| 2026-06-27 | ALG    | Austria                          |                 1 |
| 2026-06-27 | ARG    | Jordan                           |                 3 |
| 2026-06-27 | AUT    | Algeria                          |                 2 |
| 2026-06-27 | COD    | Uzbekistan                       |                 1 |
| 2026-06-27 | COL    | Portugal                         |                 1 |
| 2026-06-27 | CRO    | Ghana                            |                 2 |
| 2026-06-27 | ENG    | Panama                           |                 2 |
| 2026-06-27 | GHA    | Croatia                          |                 1 |
| 2026-06-27 | JOR    | Argentina                        |                 1 |
| 2026-06-27 | PAN    | England                          |                 1 |
| 2026-06-27 | POR    | Colombia                         |                 2 |
| 2026-06-27 | UZB    | Democratic Republic of the Congo |                 1 |